config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :posts do
    resources :comments, only: [:create, :destroy, :update]
  end
  devise_for :users
  root "welcome#index"

  get "/admin", to: "welcome#admin"

  #	get "/articles" index
  #	post "/artciles" create 
  #	delete "/articles/:id" delete 
  #	get "/articles/:id" show 
  #	get "/articles/new" new
  #	get "/articles/:id/edit" edit
  # patch "/articles/:id" update
  # put "/artciles/:id" update

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :body, presence: true
  validates :nombre, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments, :dependent => :destroy
	validates :title, presence: true, uniqueness: true
	validates :subtitle, presence: true, uniqueness: true, length: { maximum: 200 }
	validates :body, presence: true, uniqueness: true 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  extend Devise::Models
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:update, :destroy]
  before_action :set_post
 
  

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @post.comments.new(comment_params)
    @comment.post = @post
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment.post }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.post, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @post, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_post
      @post = Post.find(params[:post_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through
    def comment_params
      params.require(:comment).permit(:nombre, :post_id, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:show,:index]
	before_action :set_post, except: [:index,:new,:create]

	
	#GET /posts
	def index
		@posts = Post.paginate(page: params[:page],per_page:4).order("created_at DESC")	
	end
		
	
	def create
		
		@post = current_user.posts.new(post_params)
		if @post.save
			redirect_to @post
		else
			render :new
		end
	end
	#GET articles/:id
	def show
		@comment = Comment.new
	end 

	#GET posts/new
	def new
		@post = Post.new
	end

	def edit
	end

	#POST /posts
	def destroy
		
		@post.destroy
		redirect_to posts_path
		#@post.update(deleted_state: true)
	end

	def update
		@post = Post.find(params[:id])
		if @post.update(post_params)
			redirect_to @post
		else
			render :edit
		end
	end 

	private 

	def post_params
		params.require(:post).permit(:title,:subtitle,:body)
	end 

	def set_post
		@post = Post.find(params[:id])
	end

	

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, only: [:admin]
  def index
  end
  def admin
  	@admin = Post.paginate(page: params[:page],per_page:4).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [@post, @comment], local:true, remote:true, html: { id: "comments-form", "data-type": "json"}) do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- probando comentario -->
 
   <div class="field">
    <%= form.label :nombre %><br>
    <%= form.text_area :nombre %>
  </div>

  <div class="field">
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', posts_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @comment.nombre %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Noticias Bastian</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet" type="text/css">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  	<%= render "partials/navigation" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/partials/_navigation.html.erb
 	<header>
  		<nav class="be-red white large-padding">
  			<ul class="no-list row center-xs">
  				<li class="col-md">
  					<h1 class="no-margin" id="logo"> <%= link_to "Noticias Bastian", root_path %> </h1>
  				</li>	

          <li class="col-md">
            <%= link_to "Noticias", posts_path %>
          </li>

          <li class="col-md">
            <%= link_to "Admin", admin_path %>
          </li>


          <% if user_signed_in? %>
          <li class="col-md">
            <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %>
          </li>
           <% else %>
           <li class="col-md">
            <%= link_to "Iniciar sesión", new_user_session_path%>
          <% end %>
  				
  			</ul>
  		</nav>
  	</header>

app/views/posts/_form.html.erb
<%= form_for (@post) do |f| %>
	<% @post.errors.full_messages.each do |message| %>
		<div class="be-red white top-space">
		* <%= message %>
		</div>
	<%end%>
	 <div class="field">
 	<%= f.text_field :title, placeholder: "Titulo de la noticia", class:"form-control" %>
 	</div>
 	<div class="field">
 	 <%= f.text_area :subtitle, placeholder: "Bajada de la noticia", style:"height:100px;", class:"form-control" %>
 	</div>
	<div class="field">
 	 <%= f.text_area :body, placeholder: "Cuerpo de la noticia", style:"height:250px;", class: "form-control" %>
 	</div> 
 	<div class="field">
 		<%= f.submit "GUARDAR", class: "btn be-red white" %>
 	</div>

<%end%>

app/views/posts/edit.html.erb
<div style="width:80%;margin:0 auto;">
	<h1>Editar Noticia</h1>
	<%= render "posts/form" %>
</div>

app/views/posts/index.html.erb
 <div class="container" style="margin:0 auto;">
   <h1>Noticias en vivo</h1>
 <div class="row">
  <% @posts.each do |post| %>
    <div class="col-md-4 col-sm-6 col-xs-12 top-space">
           <p><small>Publicada el <%= post.created_at %></small></p>
         <h2><%= link_to post.title, post %></h2>
        <p><%= post.subtitle %></p>
        <hr>
        <p><%= truncate(post.body, length: 500) %></p> 
        <div class="letra">
        <p><small><%= post.comments.count %> comments</small></p> 
    </div>
  </div>
  <% end %>
</div>
</div>
<div class="top-space text-center pagination">
  <hr>
<%= will_paginate @posts %>
</div>

app/views/posts/new.html.erb
<div style="width:80%;margin:0 auto;">
	<h1>Crear Noticia</h1>
	<%= render "posts/form" %>
</div>

app/views/posts/show.html.erb
<% unless @post.user.nil? %>
<div class="top space letra">
	<p><small>
		Escrito por: <%= @post.user.email %>
	</p></small>
	<p><small>
		Publicada el: <%= @post.created_at %>
	</p></small>
</div>
<%end%>
<h1><%= @post.title %></h1>
<div>
	<p><%= @post.subtitle %></p>
</div>
<div>
	<p><%= @post.body %></p>
</div>
<div class="field">
	<h3>Comentarios</h3>
	<%= render "comments/form" %>
	<ul>
		<% @post.comments.each do |comment| %>
		<li>
			<%= comment.body %> - <%= comment.nombre %> 
		</li>
		<%end%>
	</ul>
</div>

app/views/welcome/admin.html.erb
  <% @admin.each do |post| %>
    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="post">
        <p><small>Publicada el <%= post.created_at %></small></p>
        <h2><%= link_to post.title, post %></h2> - <%= link_to "Eliminar", post, method: :delete, data: {confirm: 'Estas seguro que deseas eliminar este artículo?'}%> </h2> - <%= link_to "Editar", edit_post_path(post) %>
        <!-- <p><%= post.subtitle %></p>
        <hr>
        <p><%= post.body %></p> -->
      </div>
    </div>
  <% end %>

  <div class="top-space text-center">
          <%= will_paginate @admin %>
      </div>

<div class="row">
<div class="col-xs-12">
    <hr>
    <%= link_to 'Nuevo Post', new_post_path, class: "btn be-red white" %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="top-space text-center">
	
<h1>Bienvenido a su portal de Noticias</h1>

</div>